# Generated by Django 6.0 on 2025-12-13 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('mentor_name', models.CharField(blank=True, max_length=120)),
                ('mentor_email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('language_raw', models.CharField(blank=True, max_length=50)),
                ('academic_level', models.CharField(blank=True, max_length=10)),
                ('competences_raw', models.TextField(blank=True)),
                ('skills_list', models.JSONField(blank=True, default=list)),
                ('language_fr', models.BooleanField(default=False)),
                ('language_en', models.BooleanField(default=False)),
                ('is_dev', models.BooleanField(default=False)),
                ('is_marketing', models.BooleanField(default=False)),
                ('academic_score', models.IntegerField(default=0)),
                ('email_sent', models.BooleanField(default=False)),
                ('is_leader', models.BooleanField(default=False)),
                ('uid', models.CharField(blank=True, max_length=32)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='participants.team')),
            ],
        ),
    ]
